name: CD for Development

on:
  push:
    branches:
      - dev

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: HELLO WORLD
        run: echo "HELLO WORLD, THIS IS GITHUB ACTION!!!! ITS GOOD"
